{
 "title": "Spicenet Node Monitoring by Cumulo",
 "description": "This version of the Grafana dashboard is specifically designed for monitoring Spicenet nodes. It includes comprehensive configurations and visualizations tailored to provide real-time insights into the performance and health of your Spicenet node. By integrating Grafana with Node Exporter, this setup enables you to track critical metrics, such as Ethereum transaction status, system resource usage, and time-sensitive updates, through interactive panels and informative graphs.\n\nWith this custom monitoring solution, managing and optimizing your Spicenet nodes becomes seamless and efficient.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <img src=\"https://cumulo.pro/images/spicenet.png\" alt=\"Logo\" style=\"height: 150px;\"> <!-- Ajusta la altura según sea necesario -->\n    <h2>Spicenet Node metrics</h2>\n    <h5>by <a href=\"https://cumulo.pro\">Cumulo</a></h5>\n<h5><a href=\"https://github.com/Cumulo-pro/SpicenetTools/blob/main/monitoring/metrics.md\">Fuel-monitor docs</a></h5>\n</div>\n"
   }
  },
  {
   "title": "LATEST ROLLUP HEIGHT",
   "type": "stat",
   "description": "The latest_rollup_height metric represents the most recent rollup height in Spicenet.\n\nTracking this metric is vital for understanding the current state of the rollup and ensuring that it is up to date with the latest blocks. It provides insight into the progress and health of the rollup, which is crucial for systems relying on up-to-date block heights.",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "latest_rollup_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ERROR COUNT",
   "type": "stat",
   "description": "The error_count metric tracks the number of errors that have occurred in the Spicenet logs. It is a gauge that reflects the real-time count of errors, helping identify any issues or failures within the system.\n\nMonitoring error counts is crucial for ensuring system reliability and troubleshooting. A sudden spike in errors can indicate potential problems in the system that need attention.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "error_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "EXECUTION BLOCK",
   "type": "stat",
   "description": "The execution_block metric records the block height of the last completed execution in Spicenet. This is a gauge metric that provides insight into the progress of the system in completing block executions.\n\nTracking this metric helps operators monitor the health of the node and ensure that block execution is happening consistently. It is important for verifying that the system is processing and executing blocks as expected.",
   "gridPos": { "h": 3, "w": 8, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "execution_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "EXECUTION TIME",
   "type": "gauge",
   "description": "The execution_time metric records the time taken to process the last block in Spicenet, measured in seconds. It is a gauge metric that tracks the processing time, helping identify performance bottlenecks or delays in block execution.\n\nThis metric is useful for evaluating the system's processing efficiency and responsiveness. A sudden increase in execution time may indicate system strain or issues in processing.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "execution_time",
     "legendFormat": "total number of injected transactions in the sequencer's index"
    }
   ]
  },
  {
   "title": "LAST FINALIZED HEIGHT",
   "type": "stat",
   "description": "The last_finalized_height metric records the block height of the last finalized block in Spicenet, which corresponds to the last block in the Celestia chain. Like the previous metric, it is a gauge that reflects changes over time as new blocks are finalized.\n\nMonitoring this metric is essential to ensure that the system is consistently processing blocks and finalizing them as expected. A sudden discrepancy between latest_rollup_height and last_finalized_height may indicate an issue with block finalization.",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_finalized_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SYNC STATUS",
   "type": "stat",
   "description": "A metric that indicates whether a node in the Fuel consensus system is syncing blocks. When this metric has a value of 1, it means that the node is actively syncing blocks. Conversely, a value of 0 indicates that the node is not currently syncing blocks. Block synchronization is the process by which a node updates its copy of the blockchain by downloading the most recent blocks from other nodes in the network.",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A -  $B", "type": "math" }
   ]
  },
  {
   "title": "EXECUTION TIME",
   "type": "timeseries",
   "description": "The execution_time metric records the time taken to process the last block in Spicenet, measured in seconds. It is a gauge metric that tracks the processing time, helping identify performance bottlenecks or delays in block execution.\n\nThis metric is useful for evaluating the system's processing efficiency and responsiveness. A sudden increase in execution time may indicate system strain or issues in processing.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "execution_time",
     "legendFormat": " time taken for the latest block's execution in seconds"
    }
   ]
  },
  { "title": "Spicenet data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "HTTP REQUEST LATENCY",
   "type": "timeseries",
   "description": "The HTTP Request Latency Metric measures the time taken for HTTP requests to be processed by the Prometheus exporter. This metric is recorded as a histogram, allowing for the analysis of response time distribution across different time intervals.\n\nTracking request latency is crucial for identifying performance bottlenecks, ensuring system responsiveness, and diagnosing potential delays in HTTP request handling.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "prometheus_exporter_request_duration_seconds_bucket{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP RESPONSE SIZE",
   "type": "stat",
   "description": "The HTTP Response Size Metric measures the size of the HTTP response generated by the Prometheus exporter, recorded in bytes. This metric is a gauge, meaning it can increase or decrease over time, reflecting changes in response payload size.\n\nTracking this metric is important for optimizing resource usage, identifying unusually large responses, and ensuring efficient communication between Prometheus and its clients.\n\nValue Interpretation:\n\nHigher values may indicate that Prometheus is returning more data than usual, potentially leading to increased network and memory usage.\nConsistently high values may suggest the need for query optimization or data reduction.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_exporter_response_size_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL HTTP REQUESTS",
   "type": "timeseries",
   "description": "The Total HTTP Requests Metric records the total number of HTTP requests received by the Prometheus exporter. This metric is a counter, meaning it only increases over time, reflecting the cumulative number of requests processed since the exporter started running.\n\nTracking this metric is essential for monitoring service demand, detecting unusual request spikes, and ensuring that the system can handle incoming traffic efficiently.\n\nValue Interpretation:\n\nEach increment in this counter represents a new processed request.\nThe absolute value of this metric indicates the total number of requests since data collection started.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "prometheus_exporter_requests_total{job=\"$job\"}",
     "legendFormat": "total number of HTTP requests received by the Prometheus exporter"
    }
   ]
  },
  {
   "title": "BATCH PUT LATENCY",
   "type": "timeseries",
   "description": "The Batch Put Latency Metric measures the time taken for batch put operations in the Rockbound Schema, recorded in seconds. This metric is represented as a histogram, allowing detailed analysis of latency distribution across different time intervals.\n\nMonitoring batch put latency helps assess database performance, detect bottlenecks in data storage, and ensure that writes to the database remain efficient.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "rockbound_batch_put_latency_seconds_bucket{job=\"$job\"}",
     "legendFormat": "number of duplicate block parts received by the node"
    }
   ]
  },
  {
   "title": "ROCKBOUND PUT DATA SIZE",
   "type": "timeseries",
   "description": "The Rockbound Put Data Size Metric measures the size of data (in bytes) written to different Column Families (CFs) in the Rockbound Schema. This metric is recorded as a histogram, allowing detailed analysis of the distribution of data sizes across different thresholds.\n\nTracking this metric is essential for optimizing database performance, monitoring write efficiency, and ensuring storage is used effectively.\n\nValue Interpretation:\nEach bucket represents the number of data writes that fall within the specified size threshold for a given column family.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rockbound_put_bytes_bucket{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVERAGE BATCH PUT LATENCY ",
   "type": "timeseries",
   "description": "The AVERAGE BATCH PUT LATENCY metric measures the average time taken for batch put operations in the Rockbound Schema. It is calculated by dividing the total sum of latencies (rockbound_batch_put_latency_seconds_sum) by the count of operations (rockbound_batch_put_latency_seconds_count). This provides the average latency per batch put operation in seconds.\n\nMonitoring this metric helps assess the overall efficiency of database write operations, identify performance bottlenecks in data storage, and ensure that the system remains efficient under varying workloads.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rockbound_batch_put_latency_seconds_sum{job=\"$job\"} / rockbound_batch_put_latency_seconds_count{job=\"$job\"}",
     "legendFormat": "numerical value representing the mean time per batch put"
    }
   ]
  },
  {
   "title": "SCHEMADB GET DATA SIZE",
   "type": "timeseries",
   "description": "The SchemaDB Get Data Size Metric measures the size of data (in bytes) retrieved from different Column Families (CFs) in SchemaDB. This metric is recorded as a histogram, allowing analysis of the distribution of retrieved data sizes across different thresholds.\n\nMonitoring this metric helps evaluate query efficiency, optimize database read operations, and identify potential inefficiencies in data retrieval.\n\nValue Interpretation:\nEach bucket represents the number of data retrieval operations that fall within the specified size threshold for a given column family.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    { "expr": "schemadb_get_bytes_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SCHEMADB GET LATENCY",
   "type": "timeseries",
   "description": "The SchemaDB Get Latency Metric measures the time taken (in seconds) for database read operations across different Column Families (CFs). This metric is recorded as a histogram, allowing analysis of the distribution of read latencies across different thresholds.\n\nMonitoring this metric helps optimize database performance by identifying potential bottlenecks and ensuring efficient query execution.\n\nValue Interpretation:\nEach bucket represents the number of data retrieval operations that fall within the specified latency threshold for a given column family.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "schemadb_get_latency_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}